### ISSUE TITLE
ignore the pose

### ISSUE THREAD

**Issue by pytyeah** [Blade6570/icface#11]
Thanks for your great work!
But I have a question now. How can I ignore the pose and just focus on the facial expression?I've tried to keep its variables constant, but that doesn't seem ideal...
Waiting for your reply

**Comment by Blade6570** [comment]
Hi, Thanks for appriciating our work. 
To keep the pose same on the source image, you have to replace each driving frame pose parameters with source pose parameters. 

I hope it helps.

**Comment by pytyeah** [comment]
> Hi, Thanks for appriciating our work.
> To keep the pose same on the source image, you have to replace each driving frame pose parameters with source pose parameters.
> 
> I hope it helps.

Thank you very much!
And I have another question, how can i deal with more than one images at the same time? I want to generate multiple images of different faces by using one .csv file.
I'd appreciate it if you could help me!

**Comment by Blade6570** [comment]
Hi, 
I think you need to keep the CSV path fixed in the arguments. Then there are two ways to achieve this. 1. By submitting a separate job for each images and changing the `which_ref` argument with image path. You can even write a script with `os.system` command to submit those jobs automatically. 
2. You need to change the `test.py` file with a for loop and give multiple image paths in `which_ref` arguments. 

I hope it helps.
Thanks Soumya

**Comment by pytyeah** [comment]
Thanks a lot!


| |
pyt
|
|
pytyeah@163.com
|
签名由网易邮箱大师定制
On 5/20/2020 02:42，Soumya Tripathy<notifications@github.com> wrote：

Hi,
I think you need to keep the CSV path fixed in the arguments. Then there are two ways to achieve this. 1. By submitting a separate job for each images and changing the which_ref argument with image path. You can even write a script with os.system command to submit those jobs automatically.
2. You need to change the test.py file with a for loop and give multiple image paths in which_ref arguments.

I hope it helps.
Thanks Soumya
